### PR TITLE
update mirror bot to mirror to bitbucket

### PR DESCRIPTION
**Pull request by ngoldbaum**

### CODE REVIEW

**Comment by matthewturk** [comment]
Any reason this can't be merged?

**Comment by ngoldbaum** [comment]
Kacper needs to actually enable this on fido. Just merging it won't make the bot start working.

**Comment by Xarthisius** [comment]
Just merging would actually work :) but I need to figure out how to pass yt-fido's bb credentials

**Comment by ngoldbaum** [comment]
Ah yes, I was just relying on SSH. I think you can use an [access key](https://confluence.atlassian.com/bitbucket/use-access-keys-294486051.html) or [oauth](https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html#OAuthonBitbucketCloud-Accesstokens).

**Pull request merged**
